export const ugandanUniversities = [
  'Makerere University',
  'Kampala International University',
  'Uganda Christian University',
  'Makerere University Business School',
  'Uganda Martyrs University',
  'Kyambogo University',
  'Islamic University in Uganda',
  'Busitema University',
  'Mbarara University',
  'Gulu University',
];

export const sampleListings = [
  {
    title: 'MacBook Pro 13" 2020 - Like New',
    description: 'Excellent condition MacBook Pro 13" from 2020. Intel i5 processor, 8GB RAM, 256GB SSD. Comes with original charger and box. Perfect for students doing programming or design work.',
    price: 2800000,
    condition: 'like-new',
    location: 'Makerere University',
    negotiable: true,
    images: ['https://images.pexels.com/photos/18105/pexels-photo.jpg'],
    category: 'electronics',
    views: 128,
  },
  {
    title: 'Mini Fridge - Perfect for Dorm',
    description: 'Compact mini fridge ideal for dorm rooms. Energy efficient, quiet operation. 1.7 cubic feet capacity. Great for keeping drinks and snacks cold. Only used for one semester.',
    price: 180000,
    condition: 'good',
    location: 'Kampala International University',
    negotiable: true,
    images: ['https://images.pexels.com/photos/2343467/pexels-photo-2343467.jpeg'],
    category: 'furniture',
    views: 95,
  },
  {
    title: 'Portable Washing Machine',
    description: 'Small portable washing machine perfect for student accommodation. Twin tub design - wash and spin dry. Saves time and money on laundry. Easy to move and store.',
    price: 320000,
    condition: 'good',
    location: 'Uganda Christian University',
    negotiable: false,
    images: ['https://images.pexels.com/photos/5591581/pexels-photo-5591581.jpeg'],
    category: 'other',
    views: 67,
  },
  {
    title: 'Comfortable Reading Chair',
    description: 'Cozy reading chair with cushioned seat and backrest. Perfect for studying or relaxing. Durable wooden frame with fabric upholstery. Great condition, no tears or stains.',
    price: 150000,
    condition: 'good',
    location: 'Makerere University',
    negotiable: true,
    images: ['https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg'],
    category: 'furniture',
    views: 82,
  },
  {
    title: 'Wooden Study Desk',
    description: 'Solid wood study desk with spacious surface and drawer. Perfect for laptop, books, and stationery. Sturdy construction, no wobbling. Ideal for focused study sessions.',
    price: 280000,
    condition: 'good',
    location: 'Makerere University',
    negotiable: true,
    images: ['https://images.pexels.com/photos/667838/pexels-photo-667838.jpeg'],
    category: 'furniture',
    views: 104,
  },
  {
    title: 'Engineering Textbook Bundle',
    description: 'Complete set of engineering textbooks for Year 2. Includes Mechanics, Thermodynamics, and Materials Science. Good condition with minimal highlighting. Save money compared to buying new!',
    price: 120000,
    condition: 'good',
    location: 'Makerere University',
    negotiable: true,
    images: ['https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg'],
    category: 'books',
    views: 143,
  },
  {
    title: 'Queen Size Mattress',
    description: 'Comfortable queen size mattress in excellent condition. Memory foam top layer for extra comfort. Only 6 months old, selling because moving to smaller accommodation. No stains or damage.',
    price: 380000,
    condition: 'like-new',
    location: 'Kampala International University',
    negotiable: true,
    images: ['https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg'],
    category: 'furniture',
    views: 91,
  },
  {
    title: 'PlayStation 5 Console',
    description: 'PS5 Console with controller and 3 games (FIFA 24, Spider-Man, God of War). Excellent condition, rarely used. All cables and original packaging included. Great deal!',
    price: 2200000,
    condition: 'like-new',
    location: 'Makerere University',
    negotiable: false,
    images: ['https://images.pexels.com/photos/9072219/pexels-photo-9072219.jpeg'],
    category: 'electronics',
    views: 215,
  },
];
